server:
  port: 8081
spring:
  task:
    scheduling:
      pool:
        size: 1
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show-sql: true
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
redis:
  host: ${AWS_EC2_REDIS_HOST}        # Redis 서버 호스트 (AWS EC2 호스트 이름 또는 IP)
  port: 6379                        # Redis 포트 (기본값: 6379)
  password: ${REDIS_PASSWORD}       # Redis 인증 비밀번호 (없다면 생략 가능)
  timeout: 2000                     # 연결 타임아웃 (ms 단위)
  lettuce:
    pool:
      max-active: 10              # 최대 연결 수
      max-idle: 5                 # 유휴 상태 연결의 최대 수
      min-idle: 1
naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
  location-search-url: ${NAVER_LOCATION_SEARCH_URL:https://openapi.naver.com/v1/search/local.json}
