server:
  port: 8081
spring:
  task:
    scheduling:
      pool:
        size: 1
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: 6379
      password: ${SPRING_REDIS_PASSWORD}
      timeout: 2000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        ddl-auto: none
        show-sql: true
        cache:
          use_query_cache: false
          use_second_level_cache: false
          use_structured_entries: false
          use_minimal_puts: false
          region:
            factory_class: org.hibernate.cache.internal.NoCachingRegionFactory
        generate_statistics: false
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
  devtools:
    restart:
      enabled: false

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
  location-search-url: ${NAVER_LOCATION_SEARCH_URL:https://openapi.naver.com/v1/search/local.json}
