spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: 6379
      password: ${SPRING_REDIS_PASSWORD}
      timeout: 2000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
